spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-db4amoss728c73a5r7ag-a.singapore-postgres.render.com:5432/lms_db_xi46?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lms_db_xi46_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AB8f8GY8M1RVpf1zKW2TwWkfGPuFNYbS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

